import { chromium, devices } from '@playwright/test';
const browser = await chromium.launch();
const p = await browser.newPage({ viewport: { width: 375, height: 800 }, deviceScaleFactor: 2 });
await p.goto('http://localhost:3001/', { waitUntil: 'networkidle' });
await p.waitForTimeout(800);
const cls = await p.$eval('header', el => el.className);
const bg = await p.$eval('header', el => getComputedStyle(el).backgroundColor + ' | ' + getComputedStyle(el).position);
console.log('header class:', cls);
console.log('header bg/pos:', bg);
await p.screenshot({ path: '/tmp/lp-shots/nav-top.png', clip: { x: 0, y: 0, width: 375, height: 120 } });
await browser.close();
