"""Tests for sync_soul.py. Run from the skill root:
    python -m unittest scripts.test_sync_soul -v
or  python scripts/test_sync_soul.py
"""
from __future__ import annotations

import sys
import tempfile
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import sync_soul


class SyncSoulTests(unittest.TestCase):
    def setUp(self) -> None:
        self._tmp = tempfile.TemporaryDirectory()
        self.tmp = Path(self._tmp.name)
        self._orig_targets = sync_soul.GLOBAL_TARGETS
        self._orig_mirrors = sync_soul.SKILL_MIRRORS
        self.target = self.tmp / "CLAUDE.md"
        sync_soul.GLOBAL_TARGETS = {self.target: "# Global Judgment Rules\n\nheader\n\n"}
        sync_soul.SKILL_MIRRORS = []
        self._orig_argv = sys.argv
        sys.argv = ["sync_soul.py"]

    def tearDown(self) -> None:
        sync_soul.GLOBAL_TARGETS = self._orig_targets
        sync_soul.SKILL_MIRRORS = self._orig_mirrors
        sys.argv = self._orig_argv
        self._tmp.cleanup()

    def test_soul_body_starts_at_marker(self) -> None:
        body = sync_soul.soul_body()
        self.assertTrue(body.startswith(sync_soul.BODY_MARKER))

    def test_compact_parity_with_canonical(self) -> None:
        if not hasattr(sync_soul, "parity_errors"):
            self.skipTest("this copy has no compact rendering")
        self.assertEqual(sync_soul.parity_errors(), [])

    def test_generates_missing_global_file(self) -> None:
        sync_soul.main()
        content = self.target.read_text(encoding="utf-8")
        self.assertTrue(content.startswith("# Global Judgment Rules"))
        self.assertIn(sync_soul.BODY_MARKER, content)

    def test_regenerates_own_stale_file(self) -> None:
        self.target.write_text("# Global Judgment Rules\n\nstale body\n", encoding="utf-8")
        sync_soul.main()
        self.assertIn(sync_soul.BODY_MARKER, self.target.read_text(encoding="utf-8"))

    def test_skips_foreign_global_file(self) -> None:
        if not hasattr(sync_soul, "FOREIGN_GUARD") and "not generated by this script" not in (
            Path(sync_soul.__file__).read_text(encoding="utf-8")
        ):
            self.skipTest("this copy has no foreign-file guard")
        foreign = "# My own instructions\ndo not clobber\n"
        self.target.write_text(foreign, encoding="utf-8")
        sync_soul.main()
        self.assertEqual(self.target.read_text(encoding="utf-8"), foreign)


if __name__ == "__main__":
    unittest.main()
